skillTypeAry = 
	["CAD/CAM","Miscellaneous","Networking","New Media","Project Management","Qualitsy Assurance",
	 "Technical Recruitsing","Tech Sales/Marketing","Technical Writser","Unix","Windows develop",
	 "Office Applications","AS/400","Data Warehousing","Database Systems","E-Commerce/Internet",
	 "ERP","Executive Level","Handware","Help desk","Legacy Systems"];

skillItemAry = [
    ["CADAM","AUTOCAD","CATIA"],
    ["Accounting","Administrative Support","Analyst","Business Developer","Customer Service","Human Resources","Traditsional Engineer"],
    ["ADSL","ATM","Banyan","Bay","cc:Mail","Cisco","CNE","Engineer","Firewall","Frame Relay","Hubs/Routers","ISDN","LAN/WAN","Lotus","Mail","MCP","MCSE","Motorola","NetWare","PBX","RF","Securitsy","SMS","SNA","Sniffer","Sonet","Telecom","Windows NT/2000","TCP/IP","VPN","X.25","Windows xp","Advance Link","Appletalk","Asynch","Banyan Vines","Bay Networks","Bridges","CC mail","CDMA","Cisco Routers","Ethernet","GSM","HP Open View","ISAM","LanManager","LanServer","Lantastic","Lap Link","Lease Lines","Load Balancing","MS Exchange","Multinet","MVX","Netbios","NetMaster","NetWork Cards","Optical Fibre","PABX","Pathworks","Reflection","Relay Gold","Routers","WAN","X400"],
    ["Adobe Photoshop","Corel Draw","Director","Flash","Games","Graphics","Illustrator","Image/Imaging","Mac","Multimedia","PageMaker","PowerPoint","Quark","Shockwave","Vizact 2000","Dreamweaver","Fireworks/Frontpage","3dStudio","3dStudio MAX","After Effects","Alias studio","Authorware","Cakewalk","Director","Freehand","Frontpage","GoLive","HomeSitse","Lightwave","Maya","Microsoft Photo Edits","MS Publisher","NetObjects Fusion","Photoshop","Protal","Quark Express","Shockware","Softimage","Strata","Streamline"],
    ["Capacitsy Planning","Change Management","Configuration Management","Contingency Planning","Defect Management","Disaster Recovery","ISO","Methodology","Metrics","Microsoft Project","PMI","Procurement","RISK Management","Scope Management","SDLC","SEI/CMM","Business Analyst","Project Manager"],
    ["Change Management","Configuration Management","Defect Management","Metrics","PVCS","QA/Tester","Qualitsy Control","SEI/CMM","Source Safe/Visual Source S","SQA","Test Scripts","Version Control","WinRunner","Xrunner","XDE Tester","WebLOAD","WebFT","WAS","VisualTest","TradeRecord","TestTrade Pro","TestParter","TestManager","TestDirector","TestBed","SilkTest","SilkRadar","SilkPlan Pro","SilkPerformer","Robot","Rational Test RealTi","Rational Quantify","Rational Purify","Rational PureCoverag","QuickTest Professional","QARun","QALoad","QADirector","PVCS Tracker","Optimizeits Suitse","OpenSTA","Mantis","Logiscope","Loadrunner","Junits","JTest","E-Test suitse","DevPartner Studio","Code Test","ClearQuest","Cantata","C++test","Bugzilla","Astra QuickTest","Astra LoadTest","ACT"],
    ["Account Executive","Manager","Recruitser","Business-to-Business Market","Consultants","Contigency Search","Direct Sourcing","Outsourcing","Retained Search"],
    ["Account Executive","Marketing Representative","Sales Representative","Strategist","Business Demographics","Call Point","Cloning customers","Coding","DatabaseMarketing","Lifetime value VPN","Sales Cycle","SFA Tools","SIC Code"],
    ["Corel Draw","HTML","PowerPoint","Publisher","RoboHelp","Visio","Word","WordPrefect","XML","Acrobat","ForeHelp","Premier 2000","FrameMarker","Online Helpp","Paint Shop Pro"],
    ["AIX","C/C++","CORBA","Embedded","HP-UX","Java","Linux","OpenView","Perl","Scripts","Sun Solaris","TCL/TK","Tivoli","Tuxedo","*BSD","Kernels"],
    ["Access","ActiveX","C/C++","COM/DCOM","COOL:Gen","CORBA","Crystal Reports","Delphi","Developer/Designer 2000","DNA","Forte","Fox Pro","GUI","Java","MCSD","MFC/ATL","OLAP","00","PowerBuilder","Pro*C","Smalltalk","Visual Basic","Visual C++","Win32","Visual FoxPro",".NET","C#","Ant","BizTalk","eMbedded Visual C++","Fortran","FoxBASE+","MapInfo","Mobile","Rational Clearcase","StarTeam","Transact-SQL","UML","Visual SourceSafe1","WIN CVS","Wireless","Visual Studio"],
    ["OutLook Express","OutLook","Netscape Communicator","MS OneNote","Internet Explorer","MS PowerPoint","MS Project","Lotus 123","MS Excel"],
    ["CL","COBOL","ILE","RPG","RPG400","RPGIII/IV","Synon"],
    ["CASE","Data Analyst","Data Architsect","Data Marts","Data Mining","Data Modeling","ERwin","SAS"],
    ["Access","Capacitsy Planning","Database Administrator","DB2","FoWindows XPro","Informix","Oracle","Progress","SQL","SQL Server","Sybase","Jasmine","CMMS","Interbase","SAPDB"],
    [".NET","ActiveX","ASP","ASP.NET","BroadVision","C#","CGI","Cold Fusion","PHP","CSS","DHTML","Dreamweaver","E-Commerce","E-Commerce Platforms","EDI","EJB","Electronic Payment","HTML","IIS","J2EE","Java","JavaScript","JSP","PERL","Securitsy","VB.NET","VBScript","Visual J++","VRML","Web Servers","Web Master/Developer","WebLogic","WebSphere","XML/XSLT","Broad Vision","MOM","Visual Basic"],
    ["BAAN","Great Plains","JD Edwards","Lawson","Oracle","PeopleSoft","SAP","ACL","Autre Stat","Multi Term","Navision","Siebel","Spss","Swift"],
    ["Business Development","Financial Services","Marketing/Sales","Senior Executive","Technology"],
    ["Cable Modem","Chipware","Circuits Design","Drivers","Embedded Systems","FireWare","Hardware","IEEE","Operating System Designers","Digital Product","Mobile Network","Mobile Phone"],
    ["AS/400","CICS","UNIX","Windows 95","Windows 98","Windows NT/2000","Windows XP","Handware","Lotus Notes","Mac","MS Office","Network","Novell","PC/Desktop","MS Exchange"],
    ["ADABAS","Assembler","CA-","CICS","COBOL","DB2","DEC/VAX","FOCUS","GEAC","IDMS","IMS","MicroFocus","MQSeries","MVS","Natural","OS/2","OS/390","PL/2","REXX","SAS","Tape Operator","Teradata","VM","VSAM","TSO"]
];